version: '3.8'

services:
  todoapp:
    build: .
    command: >
      /usr/local/bin/todors
    depends_on:
      - postgres
      - migrations
    environment:
      DATABASE_URL: postgres://postgres:qwerty@postgres/todosdb
    ports:
      - "8081:8081"

  migrations:
    image: izissise/diesel-cli:latest
    command: >
      diesel setup &&
      diesel migration run
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:qwerty@postgres/todosdb
    volumes:
      - .:/volume
    working_dir: /volume

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: